<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AnyHttpProxy</RootNamespace>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <!-- Pakiet sam kopiuje msquic.dll obok exe przy publikacji single-file (buildTransitive). -->
    <PackageReference Include="Tailcat.Link" Version="0.5.3" />
  </ItemGroup>

</Project>
